---
volumes:
  tempo-dev-2-vm-1-data: {}

services:

  memcached:
    container_name: tempo-memcached-dev-2-vm-1
    image: memcached:1.6.40
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Number of threads to use
    restart: unless-stopped
    networks:
      - grafana

  tempo:
    container_name: tempo-dev-2-vm-1
    image: grafana/tempo:2.10.2
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - tempo-dev-2-vm-1-data:/var/tempo
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4327:4317"  # otlp grpc
      - "4328:4318"  # otlp http
    restart: unless-stopped
    depends_on:
      - memcached
    networks:
      - grafana

networks:
  grafana:
    name: grafana
    driver: bridge
    attachable: true